"use strict";

  const TEXT = {
    nav_home: ["主页", "Home"], nav_log: ["日志", "Log"], nav_settings: ["设置", "Settings"],
    volume: ["音量", "Volume"], direct_volume: ["点击直接输入音量", "Click to enter volume"],
    volume_down: ["音量 −1", "Volume −1"], volume_up: ["音量 +1", "Volume +1"],
    mute: ["静音", "Mute"], unmute: ["恢复音量", "Restore volume"], mute_note: ["已静音，点击喇叭图标恢复", "Muted — click the speaker icon to restore"],
    input_source: ["输入源", "Input Source"], device_info: ["设备信息", "Device Info"],
    ip_address: ["IP 地址", "IP Address"], mac_address: ["MAC 地址", "MAC Address"], model: ["型号", "Model"], firmware: ["固件", "Firmware"], health_last_check: ["最近心跳", "Last heartbeat"], health_last_action: ["最近动作", "Last action"], health_last_issue: ["最近异常", "Last issue"], health_none: ["暂无", "None yet"], health_now: ["刚刚", "Just now"], health_seconds_ago: ["$ 秒前", "$s ago"], failed: ["失败", "Failed"],
    connected_on: ["已连接 · 开机", "Connected · On"], connected_standby: ["已连接 · 待机", "Connected · Standby"], disconnected: ["未连接", "Disconnected"],
    no_device: ["未找到设备", "No device found"], power_on: ["开机", "On"], power_standby: ["待机", "Standby"],
    waking: ["正在唤醒", "Waking"], waiting_confirmation: ["等待音箱确认…", "Waiting for speaker confirmation…"], entering_standby: ["正在待机", "Entering standby"],
    standby_help: ["扬声器处于待机状态。唤醒后即可调节音量和输入源。", "The speaker is in standby. Wake it to control volume and input."],
    configure_speaker_help: ["未找到扬声器——去设置选择扬声器并扫描一下。", "No speaker found — choose and scan for a speaker in Settings."], configure_speaker: ["去设置扫描", "Set up speaker"],
    app_log: ["应用日志", "Application Log"], refresh: ["刷新", "Reload"], open_folder: ["打开文件夹", "Open Folder"], log_file: ["日志文件", "Log file"], today_log: ["今天", "Today"],
    search_log: ["搜索日志…", "Search logs…"], clear_search: ["清除搜索", "Clear search"], min_level: ["最低级别", "Min level"],
    reset_filters: ["重置筛选", "Reset filters"], no_match: ["没有匹配「$」的日志行", "No lines matching \"$\""], no_level: ["该级别下没有日志", "No logs at this level"],
    showing: ["显示", "Showing"], lines: ["行", "lines"], hidden_below: ["已隐藏 $ 以下", "hiding below $"], back_to_bottom: ["回到底部", "Back to bottom"],
    level_info: ["全部", "All"], level_step: ["步骤", "Step"], level_state: ["状态", "State"], level_event: ["事件", "Event"], level_warn: ["警告", "Warn"], level_error: ["错误", "Error"],
    severity_tip: ["$ 及以上，共 $ 行", "$ and above · $ lines"],
    saved: ["已保存", "Saved"], general: ["通用", "General"], language: ["语言", "Language"], language_desc: ["界面显示语言", "Interface display language"],
    speaker: ["扬声器", "Speaker"], default_input: ["默认输入源", "Default Input Source"], default_input_desc: ["App 唤醒扬声器时自动切到这个输入", "Selected whenever the app wakes the speaker"],
    target_speaker: ["目标扬声器", "Target Speaker"], target_desc: ["MAC 是身份标识，IP 只是当前地址", "The MAC is the identity; the IP is just the current address"], select_speaker: ["选择扬声器", "Select Speaker"],
    power_behavior: ["电源行为", "Power Behavior"], power_behavior_desc: ["哪些电脑事件会唤醒扬声器、哪些会让它待机。", "Which PC events wake the speaker or put it in standby."],
    enabled_rules: ["已启用 $ / $ 条规则。", "$ / $ rules enabled."], preset: ["预设", "Preset"], custom: ["自定义", "Custom"],
    simulate_events: ["模拟事件", "Simulate"], exit_simulate: ["退出模拟", "Exit simulation"], restore_recommended: ["恢复推荐", "Restore recommended"],
    test_banner: ["模拟模式已开启。点任意一行的模拟按钮，会按该行当前的规则执行一次真实动作。规则关着就不会有动作，这本身就是诊断结果。", "Simulation is on. Each button runs the current rule for that row. A disabled rule does nothing, which is itself a useful diagnostic."],
    trigger_event: ["触发事件", "Trigger Event"], wake: ["唤醒", "Wake"], standby: ["待机", "Standby"], test: ["模拟", "Test"], run_once: ["触发一次", "Run once"], all_off: ["全部关闭", "Turn all off"], all_on: ["全部开启", "Turn all on"], not_applicable: ["不适用", "N/A"], rule_disabled_simulation: ["规则已关闭，模拟不会有动作", "This rule is off; simulation will take no action."],
    screen_warning: ["屏幕熄灭会让扬声器待机，但屏幕点亮不会唤醒它。你需要手动开机，或同时勾上「屏幕开关 · 唤醒」。", "Display-off puts the speaker in standby, but display-on will not wake it. Turn it on manually, or also enable Display Power · Wake."],
    table_foot: ["点击列标题可整列开关。改动即时生效。", "Click a column header to toggle the whole column. Changes save instantly."], table_foot_test: ["模拟会真实控制扬声器，当前状态见主页。", "Simulations control the real speaker; see current state on Home."],
    windows_startup: ["Windows 启动", "Windows Startup"], start_on_login: ["登录时自动运行", "Run when I sign in"], start_on_login_desc: ["关闭后会同时移除任务计划和注册表项；再次开启时默认使用无需管理员权限的注册表 Run", "Turning this off removes both entries; enabling it again defaults to Registry Run, which needs no administrator permission"], startup_method: ["注册方式", "Registration method"], startup_task: ["任务计划程序", "Task Scheduler"], startup_registry: ["注册表 Run", "Registry Run"], startup_task_desc: ["任务计划程序会在登录时启动。首次创建或清理旧任务时可能需要管理员批准。", "Runs at sign-in through Task Scheduler. Creating or cleaning up a task may need administrator approval."], startup_registry_desc: ["最简单的当前用户开机自启方式，不需要额外权限。", "The simplest per-user startup method; no additional permission is needed."], startup_active: ["已生效 · $", "Active · $"], startup_inactive: ["未注册开机自启", "Not registered to run at startup"], startup_checking: ["正在检查开机自启…", "Checking startup registration…"], startup_applying: ["正在应用 · $", "Applying · $"], startup_disabling: ["正在关闭开机启动…", "Disabling startup…"],
    dlg_sub: ["选择这个 App 要控制的 KEF 扬声器。", "Choose the KEF speaker this app should control."], scanning: ["正在扫描局域网…", "Scanning your network…"], checked_devices: ["已检查 $ 台设备", "checked $ devices"], scan_complete: ["扫描完成，找到 $ 台。", "Scan complete, found $."], current_included: ["已包含你当前的扬声器。", "Your current speaker is included."], rescan: ["重新扫描", "Rescan"], no_speaker: ["没有扫描到扬声器", "No speakers found"], manual_link: ["没找到？手动输入 IP 地址", "Not listed? Enter an IP manually"], manual_entry: ["手动指定", "Manual entry"], ip_placeholder: ["IP 地址，如 10.0.0.222", "IP address, e.g. 10.0.0.222"], mac_placeholder: ["MAC（可选）", "MAC (optional)"], cancel: ["取消", "Cancel"], apply: ["应用", "Apply"], close: ["关闭", "Close"], in_use: ["使用中", "In use"], select: ["选择", "Select"], scan_failed: ["扫描请求失败，请重试。", "Scan request failed. Please retry."],
    volume_updated: ["音量 $", "Volume $"], muted: ["已静音", "Muted"], input_changed: ["已切换到 $", "Switched to $"], settings_saved: ["设置已保存", "Settings saved"], controller_error: ["控制器错误", "Controller error"], request_failed: ["请求失败。", "Request failed."], controller_unavailable: ["控制器不可用", "Controller unavailable"], controller_unavailable_desc: ["本地控制接口未能启动，请重启应用。", "The local control interface could not start. Please restart the app."], controller_reconnecting: ["与控制器失去连接，正在重连…", "Connection to the controller was lost. Reconnecting…"],
  };
  const MESSAGE_TEXT = {
    volume_update_failed: { title: ["音量更新失败", "Volume update failed"], detail: ["扬声器未接受音量更改。{error}", "The speaker did not accept the volume change.{error}"] },
    invalid_input: { title: ["无效的输入源", "Invalid input"], detail: ["不支持该输入源。", "That input source is not supported."] },
    input_changed: { title: ["输入源已切换", "Input changed"], detail: ["已切换到 {source}。", "Switched to {source}."] },
    input_changed_unsaved: { title: ["输入源已切换", "Input changed"], detail: ["已切换到 {source}，但无法保存默认值。", "Switched to {source}, but the default could not be saved."] },
    input_change_failed: { title: ["输入源切换失败", "Input change failed"], detail: ["扬声器未接受输入源更改。{error}", "The speaker did not accept the input change.{error}"] },
    settings_invalid: { title: ["设置未保存", "Settings were not saved"], detail: ["{detail}", "{detail}"] },
    settings_saved: { title: ["设置已保存", "Settings saved"], detail: ["更改已生效。", "Changes are now active."] },
    settings_session_only: { title: ["设置已在本次会话生效", "Settings updated for this session"], detail: ["无法写入 config.json。", "config.json could not be written."] },
    target_invalid_ip: { title: ["目标未保存", "Target not saved"], detail: ["请输入有效的 IPv4 地址。", "Enter a routable IPv4 address."] },
    target_invalid_mac: { title: ["目标未保存", "Target not saved"], detail: ["请输入 12 位 MAC 地址。", "Enter a 12-digit MAC address."] },
    target_empty: { title: ["目标未保存", "Target not saved"], detail: ["请输入 IP 或 MAC 地址。", "Enter an IP address or MAC address."] },
    target_not_kef: { title: ["目标未保存", "Target not saved"], detail: ["该 IP 有响应，但不是受支持的 KEF 扬声器。", "That IP responded, but is not a supported KEF speaker."] },
    target_mac_mismatch: { title: ["目标未保存", "Target not saved"], detail: ["该 IP 属于 MAC 为 {mac} 的扬声器。", "That IP belongs to a speaker with MAC {mac}."] },
    target_failed: { title: ["目标未保存", "Target not saved"], detail: ["无法验证目标信息。{detail}", "The target details could not be validated. {detail}"] },
    target_not_saved: { title: ["目标未保存", "Target not saved"], detail: ["{detail}", "{detail}"] },
    target_verified: { title: ["目标已保存", "Target saved"], detail: ["已验证 {ip} 并保存目标。", "Verified {ip} and saved the target."] },
    target_recovered: { title: ["目标已保存", "Target saved"], detail: ["已通过 MAC 找回 {ip} 并保存。", "Recovered {ip} from the MAC address and saved it."] },
    target_mac_unverified: { title: ["目标已保存", "Target saved"], detail: ["目标已保存，但验证时扬声器未报告 MAC。", "Saved the target, but the speaker did not report its MAC during verification."] },
    target_mac_not_found: { title: ["目标已保存", "Target saved"], detail: ["已保存 MAC 目标，扬声器上线后会自动找回 IP。", "Saved the MAC target. The app will recover its IP when the speaker appears."] },
    target_unreachable: { title: ["目标已保存", "Target saved"], detail: ["已保存为连接提示；当前无法访问该地址。", "Saved the target as a connection hint; it is not reachable right now."] },
    target_session_only: { title: ["目标已在本次会话生效", "Target updated for this session"], detail: ["目标已更新，但无法写入 config.json。", "The target was updated, but config.json could not be written."] },
    startup_invalid: { title: ["开机自启设置未保存", "Startup setting was not saved"], detail: ["{detail}", "{detail}"] },
    startup_busy: { title: ["正在更新开机自启", "Startup update in progress"], detail: ["请等待当前 Windows 开机自启更新完成。", "Wait for the current Windows startup update to finish."] },
    startup_saved: { title: ["开机自启设置已保存", "Startup settings saved"], detail: ["Windows 开机自启注册已更新。", "Windows startup registration is up to date."] },
    startup_attention: { title: ["开机自启设置需要处理", "Startup settings need attention"], detail: ["{detail}", "{detail}"] },
    startup_failed: { title: ["开机自启设置未保存", "Startup setting was not saved"], detail: ["{detail}", "{detail}"] },
    unknown_test: { title: ["未知的模拟事件", "Unknown test"], detail: ["{event}", "{event}"] },
    event_disabled: { title: ["{event}：无动作", "{event}: no action"], detail: ["所选规则当前已关闭。", "The selected rule is currently off."] },
    event_no_action: { title: ["无动作", "No action"], detail: ["所选规则当前已关闭。", "The selected rule is currently off."] },
    event_running: { title: ["执行中", "Running"], detail: ["等待控制器响应…", "Waiting for the controller to respond…"] },
    event_scheduled: { title: ["已完成", "Completed"], detail: ["动作已调度 · {elapsed} ms · 扬声器：{speaker}", "Action scheduled · {elapsed} ms · Speaker: {speaker}"] },
    event_not_scheduled: { title: ["无动作", "No action"], detail: ["未调度任何动作 · {elapsed} ms · 扬声器：{speaker}", "No action was scheduled · {elapsed} ms · Speaker: {speaker}"] },
    event_completed: { title: ["已完成", "Completed"], detail: ["动作已完成 · {elapsed} ms · 扬声器：{speaker}", "Action completed · {elapsed} ms · Speaker: {speaker}"] },
    event_not_completed: { title: ["无动作", "No action"], detail: ["动作未完成 · {elapsed} ms · 扬声器：{speaker}", "No action was completed · {elapsed} ms · Speaker: {speaker}"] },
    event_failed: { title: ["失败", "Failed"], detail: ["{detail}", "{detail}"] },
    speaker_action_requested: { title: ["扬声器操作", "Speaker action"], detail: ["已请求{action}。", "{action} requested."] },
    speaker_action_running: { title: ["扬声器操作", "Speaker action"], detail: ["正在{action}。", "{action} is running."] },
    speaker_action_finished: { title: ["{action}", "{action}"], detail: ["{outcome} · {elapsed} ms", "{outcome} · {elapsed} ms"] },
    speaker_action_failed: { title: ["扬声器操作失败", "Speaker action failed"], detail: ["{action}：{detail}", "{action}: {detail}"] },
  };
